# class_registry.yml
# defines the classes for different map types

classes:
  base:
    defines:
      0: {name: Waterbody, color: "#8BBBEB"}
      1: {name: Land,     color: "#DDFFBE"}
      -1: {name: Default,  color: "#f5f2f2"}
  
  terrain:
    defines:
      0: {name: Waterbody, color: "#8BBBEB"}
      1: {name: Land,     color: "#DDFFBE"}
      -1: {name: Default,  color: "#f5f2f2"}
      #for terrain layer: mountains
      2: {name: Mountain_Extreme, color: "#6b0580", role: mountain, strength: 1.00, smooth_px: 6}
      3: {name: Mountain,         color: "#9102ad", role: mountain, strength: 0.70, smooth_px: 10}
      4: {name: Hill,             color: "#bb18db", role: mountain, strength: 0.35, smooth_px: 18}
  climate:
    defines:
      0: {name: Waterbody, color: "#8BBBEB"}
      1: {name: Land, color: "#DDFFBE"}
      -1: {name: Default,  color: "#f5f2f2"}