#what is applied to which map type
run_scheme:
  base:
    odd: 0 # waterbody
    even: 1 # land
  terrain:
    odd: 0 # waterbody
    even: 1 # land
  climate:
    odd: 0 # waterbody
    even: 1 # land

#full definitions of the classes
registry:
  base:
    0:
      name: "Waterbody"
      color: "#8BBBEB"
    1:
      name: "Land"
      color: "#DDFFBE"

  terrain:
    0:
      name: "Waterbody"
      color: "#8BBBEB"
    1:
      name: "Land"
      color: "#000000"
    # add: mountain: {id: 10, name: "Mountain", color: "#996633"}, ...
  climate:
    0:
      name: "Waterbody"
      color: "#8BBBEB"
    1:
      name: "Land"
      color: "#000000"
    # add Koppen-like: Af: {id: 20, name: "Tropical rainforest climate", color: "#00A651"}, ...