# configs/world1.yml
# image: C:/Users/nicho/Documents/World Building/MapCreator/data/raw/landamass_drawing_base.jpg
# image: C:/Users/nicho/Documents/World Building/MapCreator/data/raw/landamass_drawing_base_contrast.jpg
# image: C:/Users/nicho/Documents/World Building/MapCreator/data/processed/test_data/test_centerline_outline2.png
# image: C:/Users/nicho/Documents/World Building/MapCreator/data/processed/test_data/test_centerline_outline_filled.png
# image: C:/Users/nicho/Documents/World Building/MapCreator/data/raw/baselandmass_10282025.jpg
image: C:/Users/nicho/Documents/World Building/MapCreator/data/raw/baseland_12182025_1.jpg
class_run_scheme_configurations_path: C:/Users/nicho/Documents/World Building/MapCreator/config/class_run_scheme_configurations.yml
class_registry_path: C:/Users/nicho/Documents/World Building/MapCreator/config/class_registry.yml
out_dir: C:/Users/nicho/Documents/World Building/MapCreator/data/processed
xmin: 0
ymin: 0
xmax: 3800
ymax: 3800
crs: EPSG:3857
min_points: 3
min_area: 5.0
log_file_name: "extract_all_{now:%Y-%m-%d_%H-%M-%S}"
# verbose: True
verbose: False
compute_extent_polygons: True #true by default but specified here for clarity, if false no ocean in the base case.
